runtime: python27
api_version: 1
threadsafe: true

instance_class: B1

basic_scaling:
  max_instances: 1
  idle_timeout: 5m


libraries:
- name: flask
  version: "0.12"


handlers:
- url: /favicon\.jpg
  static_files: favicon.jpg
  upload: favicon\.jpg

- url: /.*
  script: no_frontend.app
  login: admin
