
service: loadcsv-service
runtime: python27
api_version: 1
threadsafe: true

instance_class: B2

basic_scaling:
  max_instances: 1
  idle_timeout: 5m


libraries:
- name: flask
  version: "0.12"
- name: setuptools
  version: latest
- name: ssl
  version: latest


env_variables:
  GAE_USE_SOCKETS_HTTPLIB: 'true'

handlers:
- url: /favicon\.jpg
  static_files: favicon.jpg
  upload: favicon\.jpg

- url: /.*
  script: main.app
  login: admin

